### ISSUE TITLE
"invalid padding bytes"  "object of type 'NoneType' has no len()" error

### ISSUE THREAD

**Issue by noobplayer480** [biemster/FindMy#17]
I m using big Sur 11.0.1 in VMware, iCloud services are working. 
![image.png](https://user-images.githubusercontent.com/76960147/210535396-c275b875-59fc-4af4-8a08-4d4d13a95e1c.png)

In the 1st case i used my iCloud password and got " invalid padding byte" in return and in 2 nd case i used my macbook login password and got "object of type non type has no Len()".
Any idea?

**Comment by biemster** [comment]
you should use your MacBook login password, odd that it returns no data then. do you have multiple icloud accounts on that vm?

**Comment by noobplayer480** [comment]
@biemster no sir , only one , i don't have any iPhone in my area , do u think it's bcz it doesn't have any locations reports ? 
I got succes with openhaystack but map didn't work , black screen in map bcz of VM. ![IMG_20230101_232727135.jpg](https://user-images.githubusercontent.com/76960147/210543969-b46265a0-76b5-4955-95bd-e0d0621a3cff.jpg)
