### ISSUE TITLE
No data returns

### ISSUE THREAD

**Issue by davesenior9** [biemster/FindMy#19]
Im using the FindMy_proxy and client on a established and working OHS Setup. Tags are coming in as expected. When I use the FindMy_client.py script it connects to the proxy fine, but returns 0 reports received, found: [], missing [].

Any idea where to start?

**Comment by biemster** [comment]
It seems you don't have any `.keys` files in your working directory. Did you generate any with `generate_keys.py` and deploy? Or are you trying to request keys that are deployed with OHS?

**Comment by davesenior9** [comment]
Trying to request keys that are deployed with OHS. All deployed devices were deployed organically within OHS.

**Comment by biemster** [comment]
To generate `.keys` files from OHS deployed devices you can have a look at the discussion here: https://github.com/biemster/FindMy/issues/18#issuecomment-1435990649
Let me know if you run into issues.

**Comment by davesenior9** [comment]
awesome. good to go. thanks :)

**Comment by biemster** [comment]
no problem!
