### ISSUE TITLE
Reports Received 

### ISSUE THREAD

**Issue by davesenior9** [biemster/FindMy#21]
I'm seeing a large accumulation of 'Reports Received' after deploying some Tags with a faster report rate.

Anyway to reduce the amount of 'Reports Received'? I've tried tweaking the end and start date but it appears that is not directly related to the response. I'm returns with 'datePublished' fields that aren't within the requested range.

I dont know enough about the headers to make a start at that.

Thanks :)

**Comment by biemster** [comment]
The `startDate` and `endDate` fields seem to be ignored, except if you omit them (or just `endDate`, I forgot exactly how) you only get the last 20 reports per tag. See also #7
