### ISSUE TITLE
'status': 0 field?

### ISSUE THREAD

**Issue by jrusi** [biemster/FindMy#28]
First of all thx a lot for an amazing code. 
I'm not sure if this is the right place to ask:
What is the 'status': 0 field used for? Can we use it for indicating a button press on the beacon or some other sensor data like low battery level indication?

**Comment by olivluca** [comment]
Please see https://github.com/biemster/st17h66_FindMy/issues/6

**Comment by biemster** [comment]
Yes, it's a byte you control. I believe Dahknod's FakeTag uses it as a battery indicator (https://github.com/biemster/st17h66_FindMy/issues/6), but a button press is possible too (but keep in mind you might not get the notification for an hour or so, if at all)
Also according to https://github.com/dchristl/headless-haystack/issues/15#issuecomment-1732738154 it can be used to pretend to be an iPhone, and trick the anti-tracking saveguards.

**Comment by biemster** [comment]
@olivluca beat me to the punch!

**Comment by olivluca** [comment]
I didn't know that leaving it at 0 will avoid the anti-stalking measures without the need of key rotation, so maybe it's better to leave it 0.

**Comment by biemster** [comment]
It's a bit more subtle than that, key rotation will also not prevent iPhones from displaying an alert. But it will prevent tracking based on MAC address.
Setting the status to 0x00 apparently will trick an iPhone into thinking it is another iPhone, and not display an alert. But I did not test this yet.
