### ISSUE TITLE
how many keys max in one request?

### ISSUE THREAD

**Issue by humpataa** [biemster/FindMy#33]
just wondering ... have you ever noticed a limit how many keys one post can include?

**Comment by biemster** [comment]
I've never tried this, but I've heard rumors about a limit of 256. Could you report back here after you tested this?

**Comment by Chapoly1305** [comment]
@biemster @humpataa 
just tested, [1,96] are allowed. Will fail on 97th. The size of response seems irrelevant. 

I have tested to get 96 device keys at one request and received a 284,512 Bytes response that contains 96 keys' reports.

**Comment by biemster** [comment]
Thanks @Chapoly1305 !

**Comment by humpataa** [comment]
Hmm, I've been requesting data for over 280 keys at once lately, once per hour, haven't seen a problem.
But as you seem to be sure ... I wasn't actually watching the response I must admit (pushing the response right into db).
Will take an eye on this.

**Comment by Chapoly1305** [comment]
> Hmm, I've been requesting data for over 280 keys at once lately, once per hour, haven't seen a problem. But as you seem to be sure ... I wasn't actually watching the response I must admit (pushing the response right into db). Will take an eye on this.



Much appreciated for your feedback, it turns out to be a coding issue of my program. Seems there is no a noticeable limit for this query yet. I have just given another test,  **1552 keys in one request and received all of their reports in total of 1,576,864 Bytes**.
