### ISSUE TITLE
New data is being returned

### ISSUE THREAD

**Issue by Itheras** [biemster/FindMy#52]
Some Tags are now returning data that don't fall in the EC point or are invalid . 

Never seen these before.

examples below

Failed to decode elliptic curve point: Invalid EC key.
Data slice [5:62]: 0204974573496425429143fc57889425298283dc915e4fd6097dced968236b76dcf00db10aa989aac60196465b653089d4ef655a5c8a81a16d

Failed to decode elliptic curve point: Unsupported elliptic curve point type
Data slice [5:62]: 010443ed3135cec20b7505c051ddac14d49ea611da82b32cdb8f306f0c0ce54e2652e61194e9208a9df0266265732df2834d87c4e3c93cc1ae

**Comment by humpataa** [comment]
Noticed that as well, it breaks the request_reports script when EllipticCurvePublicKey is called.
Since it only breaks for certain keys I have put all the code there into try/except just ignoring them. Until someone finds a better solution.

**Comment by wangwillian0** [comment]
The problem is  that there are new data coming with an extra byte at the beginning, specifically the byte 0x2b, which makes them have 89 bytes instead of the expected 88 bytes. Not sure why this is happening.

You can check the changes in my application (you are welcome to use it, there is a web interface too, it just needs to have the server running)
https://github.com/wangwillian0/openhaystack/commit/ec25a53c16681ff2cac3de1db5471a61de54837f

**Comment by wangwillian0** [comment]
> I tested a few things i believe is the second byte that needs to be removed. So if the length is 89 remove the second byte. that fixes it for me it, if i remove the first byte the timestamp goes wrong.

My mistake, the extra byte is actually the fifth byte, which in my tests always corresponded to the byte 0x00. As the original [Seemoo's paper](https://doi.org/10.2478/popets-2021-0045):

![image](https://github.com/biemster/FindMy/assets/24196338/3cdd00d9-c059-4bf9-8209-8708a62112f0)

In my tests, the sixth byte in the longer payloads have the same range of values as the fifth byte in ordinary payloads (confidence value), making the fifth the extra one.

**Comment by humpataa** [comment]
so I have added these two line before from_encoded_point is called:

```
if len(data)>88:
	data = data[0:4] + data[5:]
```

seems to decode fine and doesn't crash anymore. question still is: why has this changed and why has it changed for a few keys only?

**Comment by faceless2** [comment]
See https://github.com/malmeloo/FindMy.py/issues/27 for the same issue

**Comment by bitbutbit** [comment]
This might help you: https://github.com/MatthewKuKanich/FindMyFlipper/issues/61#issuecomment-2065364739
