### ISSUE TITLE
Issue like trusted device ?

### ISSUE THREAD

**Issue by 1v0n26** [biemster/FindMy#54]
Traceback (most recent call last):
  File "F:\workspace\python\findmy\test1\request_reports.py", line 75, in <module>
    auth=getAuth(regenerate=args.regen, second_factor='trusted_device' if args.trusteddevice else 'sms'),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\workspace\python\findmy\test1\request_reports.py", line 34, in getAuth
    j = {'dsid': mobileme['dsid'], 'searchPartyToken': mobileme['delegates']['com.apple.mobileme']['service-data']['tokens']['searchPartyToken']}
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'service-data'

**Comment by biemster** [comment]
authentication failed, you probably provided a wrong password (or did not set up a phone number with your apple id)
