### ISSUE TITLE
Add support for TLSR825X

### ISSUE THREAD

**Issue by biemster** [biemster/FindMy#61]
Lidl Parkside batteries come with a tuya BT7L module, which have a nice flasher by @pvvx and an open source SDK + toolchain:
- https://github.com/pvvx/TlsrComSwireWriter
- https://github.com/Ai-Thinker-Open/Telink_825X_SDK

The examples/8258_feature_test is already configured for a simple advertisement only, and tested to work. Single step left is to implement the FindMy advertisement.

**Comment by Systm21** [comment]
Maybe it helps... 

https://x.com/atc1441/status/1847308917988085843

**Comment by omarkhali** [comment]
> Maybe it helps...
> 
> https://x.com/atc1441/status/1847308917988085843

How to get public key

**Comment by biemster** [comment]
> How to get public key

Please read the instructions carefully, it's all there. Also please don't intrude on multiple other issues, create a new one if you need help.
