### ISSUE TITLE
KeyError: 'M2'

### ISSUE THREAD

**Issue by lococafe** [biemster/FindMy#62]
Getting this new error with a recent rebuild of FindMy. Looks like Apples response has changed?

user@server:~/FindMy$ ./request_reports.py 
Apple ID: myapplieidhere@icloud.com
Password: 
pyprovision is not installed, querying http://localhost:6969 for an anisette server
pyprovision is not installed, querying http://localhost:6969 for an anisette server
Traceback (most recent call last):
  File "/home/user/FindMy/./request_reports.py", line 72, in <module>
    auth=getAuth(regenerate=args.regen, second_factor='trusted_device' if args.trusteddevice else 'sms'),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/FindMy/./request_reports.py", line 33, in getAuth
    mobileme = icloud_login_mobileme(second_factor=second_factor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/FindMy/pypush_gsa_icloud.py", line 37, in icloud_login_mobileme
    g = gsa_authenticate(username, password, second_factor)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/FindMy/pypush_gsa_icloud.py", line 90, in gsa_authenticate
    usr.verify_session(r["M2"])
                       ~^^^^^^
KeyError: 'M2'

**Comment by biemster** [comment]
KeyError M2 means your login failed, are you sure you typed your apple id, password and 2FA correctly?

**Comment by viper-666** [comment]
Yes Apple-ID and PW are correct, else it hasn't add the Macbook to my account.
But there isn't a auth.json file.
![image_2024-11-23_192012686](https://github.com/user-attachments/assets/6d2132b4-e51c-489d-a8a9-6a9774892790)

**Comment by biemster** [comment]
> Yes Apple-ID and PW are correct, else it hasn't add the Macbook to my account. 

Yeah indeed. Really odd, I'll have to look into this in more detail. Do you maybe have another account you could try this on?

**Comment by biemster** [comment]
wut this went on another issue?

**Comment by viper-666** [comment]
No, I have only this Apple account.

**Comment by viper-666** [comment]
Oh, I found on a heise.de article that it could maybe seems that my Apple account hasn't enough Account-Score.
As I don't own a Apple device anymore and this account is old (from 2017) this may be the problem.
They say the best way is to use the AppleID on a newer iPhone.
I will look if I could find someone where I can use my AppleID on his phone.

**Comment by biemster** [comment]
That is definitely possible, you could also just make a new id on account.apple.com

**Comment by viper-666** [comment]
But than the Account-Score will never reach without using this account with a Apple device.

**Comment by biemster** [comment]
i've had good experience with new accounts, they should have icloud properly enabled. I did however have issues with old accounts from before icloud times / early versions of it..

**Comment by viper-666** [comment]
Ok, I have icloud on the old Account, I can log me in icloud with a browser.
And I can't make a new account, maybe because my phonenumber is already register in the old account.

**Comment by viper-666** [comment]
I changed my password in Apple so the 2FA was asked again.
Here ist the output:
`{'dsid': '16822494xxx', 'delegates': {'com.apple.mobileme': {'status': 1, 'status-message': 'A server problem is blocking Apple ID sign in. Try signing in later.'}}, 'status': 0}`

**Comment by biemster** [comment]
> I changed my password in Apple so the 2FA was asked again. Here ist the output: `{'dsid': '16822494xxx', 'delegates': {'com.apple.mobileme': {'status': 1, 'status-message': 'A server problem is blocking Apple ID sign in. Try signing in later.'}}, 'status': 0}`

That usually means something is off with your account, rarely a server problem (although it might be that ofc). Please try to get a new account, this is likely not an issue in the code.

**Comment by viper-666** [comment]
I get a old iPhone and put my AppleID in, now all works like expected.
Thank you very much for your support and good work!
