### ISSUE TITLE
hci.py not working as intended

### ISSUE THREAD

**Issue by siesta888** [biemster/FindMy#64]
Does the hci.py from Open Haystack still work? I have seen a few different versions of it, but they don't seem to be working on latest raspbian or deb12. They appear to run but I'm not seeing any reports generated when I try to retrieve them, I just get 0 reports. I have some ESP32 devices coming in the mail to double check, but is anyone else using hciconfig/hcitool to successfully generate reports? What OS version/kernel version are you using?

**Comment by biemster** [comment]
I did not test this for a while, do you have a bluetooth scanner like nRF Connect on your phone? That should be able to tell you immediately if it works.

**Comment by biemster** [comment]
hci.py from openhaystack is also not working for me. I remember now there was a reason I did not include a reference to it in this repository, I probably could not get it working back then and did not want to get support request tickets on it :P

It also appears to depend fully on `hcitool`, which is deprecated.
