### ISSUE TITLE
Discrepancy in AirTag location data: Find My app shows more recent locations than network reports for owned devices

### ISSUE THREAD

**Issue by Gdocal** [biemster/FindMy#66]
**Description**
There's a discrepancy between the AirTag location data available in the official Find My app and what can be retrieved through the Find My network reports, specifically for AirTags owned by the user. This issue appears to be related to how iPhones handle location reporting for their own AirTags.

**Current Behavior**
This project successfully generates keys and retrieves reports from Apple servers for a specified time period.
For AirTags connected to the user's Apple ID (owned devices), the location history decoded from these reports is less recent than what's visible in the official Find My app.
Examining a data dump from the Find My app on Mac reveals that the most recent location data for owned AirTags is marked as coming from an "owned device" (the user's iPhone).
It appears that when a user's iPhone detects its own AirTag, it updates the location in the Find My app but does not publish this data to the Find My network report server.

**Expected Behavior**
The location data retrieved through the Find My network reports should match the most recent data visible in the official Find My app, including for AirTags owned by the user and directly connected to their iPhone.

**Hypothesis**
iPhones treat owned AirTags (those linked to the same Apple ID) differently from other detected AirTags. While they update the Find My app with the latest location, they may not broadcast this information to the Find My network report server. This creates a gap between the data available through the API and what's visible in the official app for owned devices.

**Questions**
1)Is it correct that iPhones do not publish location data to the Find My network report server for AirTags linked to the same Apple ID?
2)If so, is there an alternative method to programmatically retrieve the most recent locations for owned AirTags?
3)Does Apple provide any API or service that includes this "owned device" location data?

**Comment by biemster** [comment]
The FindMy app also shows the location of the tag when it's not "lost", when it is connected to an iphone on the same account. At that point the tag is not broadcasting its "lost" advertisement, so there is noting to send to the findmy network.

Retrieving those location reports is outside the scope of this project.
