### ISSUE TITLE
No 2FA code after entering the Apple ID

### ISSUE THREAD

**Issue by Kalle-79** [biemster/FindMy#69]
I made the adjustments in “pyphush_gsa_icloud.py.” After that, there are no more error messages. I entered the Apple ID and password. Now I am supposed to enter the 2FA code. Unfortunately, I am not receiving an SMS, nor is a code being displayed on any of my Apple devices.

When I log in online via a browser to Apple, both options work fine. I either receive the code on my devices or optionally via SMS.

Could it be that Apple has made some changes to the login system again? Has anyone else experienced this problem before?

**Comment by Systm21** [comment]
There are so many issued that have been raised. There is no secret recipe, a user once made an PR where you could somehow select the device for the sms, try that.  I couldnt find it at this point.

**Comment by Kalle-79** [comment]
Unfortunately I couldn't find it either. Maybe it has something to do with the fact that it's not a device that can be approved. I'll try again later and first delete all devices except my phone number. It's not nice to remove all the devices, but maybe it's possible.



Von: System21 ***@***.***>
Gesendet: Montag, 18. November 2024 14:33
An: biemster/FindMy ***@***.***>
Cc: Carl - Caesar Knackmuß ***@***.***>; Author ***@***.***>
Betreff: Re: [biemster/FindMy] No 2FA code after entering the Apple ID (Issue #69)


There are so many issued that have been raised. There is no secret recipe, a user once made an PR where you could somehow select the device for the sms, try that. I couldnt find it at this point.

**Comment by biemster** [comment]
@Kalle-79 which changes to pypush_gsa_icloud did you make? If you have a mac you could consider running the scripts in the `monterey` branch on it, they just lift the search-party-token from the logged in user there.

**Comment by Kalle-79** [comment]
I made the adjustments specified here in “pyphush_gsa_icloud.py” because the script not only gave the error the first time it was run, but always.

https://github.com/malmeloo/FindMy.py/pull/63/commits/261979b196f1d24a1bea26400bc92937a8eead49

After making the change it worked immediately and I was able to enter my Apple ID.
Unfortunately I only have an iPad and an iPhone available. The script runs for me under Ubuntu 24.04
I can't get a Mac up and running any time soon, but I'll see what I can do.



Von: biemster ***@***.***>
Gesendet: Dienstag, 19. November 2024 14:03
An: biemster/FindMy ***@***.***>
Cc: Carl - Caesar Knackmuß ***@***.***>; Mention ***@***.***>
Betreff: Re: [biemster/FindMy] No 2FA code after entering the Apple ID (Issue #69)


@Kalle-79<https://github.com/Kalle-79> which changes to pypush_gsa_icloud did you make? If you have a mac you could consider running the scripts in the monterey branch on it, they just lift the search-party-token from the logged in user there.

**Comment by biemster** [comment]
What happens if you run `request_reports.py` with `--trusteddevice`?

**Comment by Kalle-79** [comment]
Perfect, that was the solution. I now immediately received the code on both of my devices. Whatever the reason, it doesn't work via SMS.
Thank you very much for your help and for your work on this project! Now I can continue working on the project.



Von: biemster ***@***.***>
Gesendet: Dienstag, 19. November 2024 17:41
An: biemster/FindMy ***@***.***>
Cc: Carl - Caesar Knackmuß ***@***.***>; Mention ***@***.***>
Betreff: Re: [biemster/FindMy] No 2FA code after entering the Apple ID (Issue #69)


What happens if you run request_reports.py with --trusteddevice?
